# Basic Information 
title: Xingli Fang
position: Ph.D. Candidate in Comp. Sci.
affiliation: NC State University
affiliation_link: https://www.csc.ncsu.edu/
affiliation_logo: ./assets/img/ncsu-logo-small.svg
email: xfang23 (at) ncsu.edu
# email2: 

# Search Engine Optimization (SEO)
keywords: xingli fang, fangxingli, x fang
# canonical: 
description: Xingli Fang is a Ph.D. candidate at NC State University.

# The option is used to enable the template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=GJtATkAAAAAJ
# cv_link:
# github_link:
linkedin: https://www.linkedin.com/in/xingli-fang-7817b7231/
# twitter:

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Educations
bachelor_logo: ./assets/img/neu-logo.svg
master_logo: ./assets/img/syracuse-logo.svg
phd_logo: ./assets/img/ncsu-logo.svg

# PRO
att_logo: ./assets/img/att.svg


# Footnotes
footnote: "2025 Xingli Fang"
#footnote_link:

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: PaNXfGbGqWkJPFgftLllF8IUcF-VRFKYKBMZ-BEXaa8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
