# Site settings
title: Moscatelli Group
email: davide.moscatelli@polimi.it
description: Academic webpage of Prof. D. Moscatelli Research Group
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
google_analytics:

# Footer info
affiliation: >
    Dr. Davide Moscatelli<br/>
    Full Professor <br/>
    <a href="https://www.cmic.polimi.it/" target="_blank">Chemical Engineering</a><br/>
    Giulio Natta Dept.

location: >
  <a href="https://www.polimi.it/" target="_blank">Giulio Natta Department</a><br/>
  Politecnico di Milano <br/>
  Piazza Leonardo da Vinci 32<br/>
  Milan 20133 - Italy

contact: >
    <a href="mailto:davide.moscatelli@polimi.it" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Davide via email</a> <br/>


# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
#  - name: talks
  - name: research
  - name: laboratory
  - name: team
# - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - switch_theme.sh
  - makebib.py
