cpcommittee:
  - content: "<strong>[AAAI 2026]</strong> The Fortieth AAAI Conference on Artificial Intelligence"
    link: https://aaai.org/conference/aaai/aaai-26/main-technical-track-call/

creviewer:
  - content: "<strong>[UAI 2026]</strong> 42nd Conference on Uncertainty in Artificial intelligence"
    link: https://www.auai.org/uai2026/
  - content: "<strong>[AAAI 2026]</strong> The Fortieth AAAI Conference on Artificial Intelligence"
    link: https://aaai.org/conference/aaai/aaai-26/2026-program-committee/
  - content: "<strong>[AISI 2026]</strong> The Fortieth AAAI Conference on Artificial Intelligence, Special Track on AI for Social Impact"
    link: https://aaai.org/conference/aaai/aaai-26/2026-program-committee/
  - content: "<strong>[ICML 2025]</strong> The 42nd International Conference on Machine Learning"
    link: https://icml.cc/Conferences/2025/ProgramCommittee
  ## https://icml.cc/Conferences/2025
  - content: "<strong>[VTC 2025]</strong> The 2025 IEEE 101st Vehicular Technology Conference"
    link: http://events.vtsociety.org/vtc2025-spring/wp-content/uploads/sites/45/2025/06/vtc2025spring_FPweb.pdf
  ##  https://vtsociety.org/event/conference/101st-ieee-vehicular-technology-conference
  - content: "<strong>[WANT@ICML 2024]</strong> 2nd Workshop on Advancing Neural Network Training: Computational Efficiency, Scalability, and Resource Optimization"
    link: https://want-ai-hpc.github.io/icml2024/organizers
  ## https://want-ai-hpc.github.io/icml2024/about/

conference:
  #- content: "<strong>[Feb 2025]</strong> The 41st Conference on Uncertainty in Artificial Intelligence (UAI 2025) , will serve as reviewer"
  #  link: https://www.auai.org/uai2025/
  - content: "<strong>[Feb 2025]</strong> The 42nd International Conference on Machine Learning (ICML 2025), serve as reviewer"
    link: https://icml.cc/Conferences/2025
  - content: "<strong>[Jan 2025]</strong> The 2025 IEEE 101st Vehicular Technology Conference (VTC 2025), serve as reviewer"
    link: https://vtsociety.org/event/conference/101st-ieee-vehicular-technology-conference
  - content: "<strong>[Jun 2024]</strong> 2nd Workshop on Advancing Neural Network Training: Computational Efficiency, Scalability, and Resource Optimization (WANT@ICML 2024), serve as reviewer"
    link: https://want-ai-hpc.github.io/icml2024/about/
